/**
 * EduAbroad CRM — DB Mapper
 * Converts between JavaScript camelCase (Lead interface) and
 * PostgreSQL snake_case (Supabase DB columns).
 */
import { Lead, Settings } from './types'

// ─── Lead: JS → DB ──────────────────────────────────────
export function leadToRow(lead: Lead, userId: string): Record<string, any> {
  return {
    id: lead.id,
    name: lead.name,
    phone: lead.phone,
    email: lead.email,
    city: lead.city,
    state: lead.state,
    source: lead.source,
    parent_name: lead.parentName,
    parent_phone: lead.parentPhone,
    parent_email: lead.parentEmail,
    current_education: lead.currentEducation,
    tenth_marks: lead.tenthMarks,
    twelfth_marks: lead.twelfthMarks,
    ug_cgpa: lead.ugCGPA,
    field_of_study: lead.fieldOfStudy,
    work_experience: lead.workExperience,
    gap_years: lead.gapYears,
    destination_countries: lead.destinationCountries,
    intended_degree: lead.intendedDegree,
    target_intake: lead.targetIntake,
    budget: lead.budget,
    passport_status: lead.passportStatus,
    scholarship_interest: lead.scholarshipInterest,
    test_scores: lead.testScores,
    preferred_universities: lead.preferredUniversities,
    stage: lead.stage,
    score: lead.score,
    score_label: lead.scoreLabel,
    score_reason: lead.scoreReason,
    notes: lead.notes,
    assigned_to: lead.assignedTo,
    lead_status: lead.leadStatus,
    created_at: lead.createdAt,
    follow_up_at: lead.followUpAt,
    follow_up_note: lead.followUpNote,
    service_type: lead.serviceType,
    fee_amount: lead.feeAmount,
    payment_link: lead.paymentLink,
    payment_pending_at: lead.paymentPendingAt,
    enrolled_at: lead.enrolledAt,
    applications: lead.applications,
    documents: lead.documents,
    visa_country: lead.visaCountry,
    visa_type: lead.visaType,
    visa_application_date: lead.visaApplicationDate,
    visa_interview_date: lead.visaInterviewDate,
    visa_status: lead.visaStatus,
    conversations: lead.conversations,
    sent_messages: lead.sentMessages,
    call_transcripts: lead.callTranscripts,
    zombie_resurrected: lead.zombieResurrected,
    zombie_attempts: lead.zombieAttempts,
    last_zombie_at: lead.lastZombieAt,
    drip_count: lead.dripCount,
    last_drip_at: lead.lastDripAt,
    remarks: lead.remarks,
    utm_source: lead.utmSource,
    utm_medium: lead.utmMedium,
    utm_campaign: lead.utmCampaign,
    google_click_id: lead.googleClickId,
    meta_lead_id: lead.metaLeadId,
    portal_user_id: lead.portalUserId,
    bolna_calls: lead.bolnaCalls,
    user_id: userId,
  }
}

// ─── Lead: DB → JS ──────────────────────────────────────
export function rowToLead(row: Record<string, any>): Lead {
  return {
    id: row.id ?? '',
    name: row.name ?? '',
    phone: row.phone ?? '',
    email: row.email ?? '',
    city: row.city ?? '',
    state: row.state ?? '',
    source: row.source ?? '',
    parentName: row.parent_name ?? '',
    parentPhone: row.parent_phone ?? '',
    parentEmail: row.parent_email ?? '',
    currentEducation: row.current_education ?? '',
    tenthMarks: row.tenth_marks ?? '',
    twelfthMarks: row.twelfth_marks ?? '',
    ugCGPA: row.ug_cgpa ?? '',
    fieldOfStudy: row.field_of_study ?? '',
    workExperience: row.work_experience ?? '',
    gapYears: row.gap_years ?? 0,
    destinationCountries: row.destination_countries ?? [],
    intendedDegree: row.intended_degree ?? '',
    targetIntake: row.target_intake ?? '',
    budget: row.budget ?? '',
    passportStatus: row.passport_status ?? '',
    scholarshipInterest: row.scholarship_interest ?? false,
    testScores: row.test_scores ?? {},
    preferredUniversities: row.preferred_universities ?? [],
    stage: row.stage ?? 'New Enquiry',
    score: row.score ?? 0,
    scoreLabel: row.score_label ?? '',
    scoreReason: row.score_reason ?? '',
    notes: row.notes ?? '',
    assignedTo: row.assigned_to ?? '',
    leadStatus: row.lead_status ?? 'active',
    createdAt: row.created_at ?? 0,
    followUpAt: row.follow_up_at ?? 0,
    followUpNote: row.follow_up_note ?? '',
    serviceType: row.service_type ?? '',
    feeAmount: row.fee_amount ?? 0,
    paymentLink: row.payment_link ?? '',
    paymentPendingAt: row.payment_pending_at ?? 0,
    enrolledAt: row.enrolled_at ?? 0,
    applications: row.applications ?? [],
    documents: row.documents ?? [],
    visaCountry: row.visa_country ?? '',
    visaType: row.visa_type ?? '',
    visaApplicationDate: row.visa_application_date ?? 0,
    visaInterviewDate: row.visa_interview_date ?? 0,
    visaStatus: row.visa_status ?? '',
    conversations: row.conversations ?? [],
    sentMessages: row.sent_messages ?? [],
    callTranscripts: row.call_transcripts ?? [],
    zombieResurrected: row.zombie_resurrected ?? false,
    zombieAttempts: row.zombie_attempts ?? 0,
    lastZombieAt: row.last_zombie_at ?? 0,
    dripCount: row.drip_count ?? 0,
    lastDripAt: row.last_drip_at ?? 0,
    remarks: row.remarks ?? [],
    utmSource: row.utm_source ?? '',
    utmMedium: row.utm_medium ?? '',
    utmCampaign: row.utm_campaign ?? '',
    googleClickId: row.google_click_id ?? '',
    metaLeadId: row.meta_lead_id ?? '',
    portalUserId: row.portal_user_id ?? '',
    bolnaCalls: row.bolna_calls ?? [],
  }
}

// ─── Settings: JS → DB ──────────────────────────────────
export function settingsToRow(settings: Settings, userId: string): Record<string, any> {
  return {
    id: `global-${userId}`,
    team: settings.team,
    templates: settings.templates,
    sources: settings.sources,
    theme: settings.theme,
    interakt_api_key: settings.interaktApiKey || '',
    interakt_webhook_secret: settings.interaktWebhookSecret || '',
    bolna_agent_id: settings.bolnaAgentId || '',
    bolna_api_key: settings.bolnaApiKey || '',
    google_ads_webhook_key: settings.googleAdsWebhookKey || '',
    meta_app_id: settings.metaAppId || '',
    meta_access_token: settings.metaAccessToken || '',
    meta_pixel_id: settings.metaPixelId || '',
    portal_api_url: settings.portalApiUrl || '',
    portal_api_token: settings.portalApiToken || '',
    gas_url: settings.gasUrl || '',
    gas_sender: settings.gasSender || '',
    gmail_app_password: settings.gmailAppPassword || '',
    resend_key: settings.resendKey || '',
    gemini_key: settings.geminiKey || '',
    auto_follow_up: settings.autoFollowUp || false,
    user_id: userId,
  }
}

// ─── Settings: DB → JS ──────────────────────────────────
export function rowToSettings(row: Record<string, any>): Settings {
  return {
    team: row.team ?? [{ name: 'You', branch: 'HQ' }],
    templates: row.templates ?? [],
    sources: row.sources ?? ['Google Ads', 'Meta Ads', 'Instagram', 'Website', 'Portal', 'Referral', 'WhatsApp', 'Walk-in', 'Education Fair', 'Partner Agent'],
    theme: row.theme ?? 'light',
    interaktApiKey: row.interakt_api_key ?? '',
    interaktWebhookSecret: row.interakt_webhook_secret ?? '',
    bolnaAgentId: row.bolna_agent_id ?? '',
    bolnaApiKey: row.bolna_api_key ?? '',
    googleAdsWebhookKey: row.google_ads_webhook_key ?? '',
    metaAppId: row.meta_app_id ?? '',
    metaAccessToken: row.meta_access_token ?? '',
    metaPixelId: row.meta_pixel_id ?? '',
    portalApiUrl: row.portal_api_url ?? '',
    portalApiToken: row.portal_api_token ?? '',
    gasUrl: row.gas_url ?? '',
    gasSender: row.gas_sender ?? 'goeduabroadonline@gmail.com',
    gmailAppPassword: row.gmail_app_password ?? '',
    resendKey: row.resend_key ?? '',
    geminiKey: row.gemini_key ?? '',
    autoFollowUp: row.auto_follow_up ?? false,
  }
}
